const lukla_to_phakding = [
  "co~gDk}ipOGOGM?AIMKOCGAEAICGCGMOW]WUSOIKk@aAg@gA]o@OSECGAG@G?GAEACAg@[OMCEGEAKECCCMEKGEIACCAAAECEAGEEECAIGCECAC?CACCGC",
  "c__hDaojpOELETCDCHQT[^WXGFORKLGJGHKH[VSPGBC@C@C?G@C@SBo@LUDk@JC@A@?@ABADABABC@IBI@E@QDS@K@G?G?G?KACDKLCLAJCHEDEFUNSJMBMDOBE@WDC?A??AA?A?AAACAC?CACACAAACA?AAC?A?A@C@CBCBCDCBGDA@C?EAEAGCCEAECE?EACAEAAGCECC?CAGAE?CAACIOCICCACACC?C?C?A@EDEFKRCBEFQTC@GLEJCH?FAD?F?BADAHCBEHCDAD?D?B?D?DA@A@CBABABELa@d@IDEBUJMHa@VMFKBS@IDEFGNADCFw@b@KHCTADGHGFEDCBCBGB{@HQBKFGDCD?FCNEJEDSHQ?EAA?K?E@CBA@CHAD?JAHAFCD?F?DBF?BAHABGDCB]NMJIFU`@K\\W\\_@b@OXKLo@v@GJAXGLC`@IRKP?@IBs@A]PYRIJCDIRCNg@d@WPQb@SX[V[^MVGXAHENa@V_@VQTSNIFWVWPKPc@RYf@M\\EDg@`@c@PKNQHGTi@`@a@b@k@l@INS^I^@^@PKZFXJVCTEf@GFEBJPKVCVYTw@@SEe@IYQOBGD]Ka@Oe@S[]EC_@Um@}@W]Fe@R}@@m@y@I[TKP?XQTk@h@c@XOXQt@Od@[bAIN[d@k@d@c@\\GDm@z@QTA?Q?i@WSPSPk@Ag@YONSIA?U@MTK`@Ab@c@Lq@?}Bz@e@f@[d@S\\w@j@UH{@Ck@\\c@PMKY?gAVo@FUNa@Ac@AONEHDTKRUBg@VeA\\",
  "kqchDuggpOoC_@aJkAiEQGC_By@mAk@SCcCUEIYe@Ru@Y}@[CWQCACAGAI?KAS?E?IAE?G?E@E@E@CBCDCLAT?T@LBLDVN^?BBFBLBN?@@D?B?B?D?F?B@FBF@DBFDFDFFFDB@F?D?HAJKx@CHAJADABA@A@E?_@BK?GAK?e@K}@QsBq@{@Yk@S}AQo@NSPe@Cg@HYB{@Hs@Iw@BIA{AAOAYAk@Ow@U[CSAIAU@YGKEEMWFWBI@SBUCSJ}@NOA[C[HOHSAIBC?e@?WHW?MBGAGEGKCAKAEBQFMDGDGHKBEBC@ADEBIDCBADINI@QNOFIEIFGCGBKCWEEGc@NG@MLIPQ?WFS?Q?k@NOFOBKJEJQ@A@SAc@BSIUSa@SMCOIAAg@F[CKAiAN_@HYDQ?]Ng@Dk@Jk@VyDhAsAEeF`Cy@^y@l@mAI}Bj@MC_@M[DyD_BgAAQJyAt@o@PY@O?s@U]Y]Ye@OwA]q@i@GQ?CMEQPIT"
];

const getStretch1Data = () => lukla_to_phakding;

export { getStretch1Data };
