const chhukung_to_chhukung_ri_to_chhukung_7 = {
	type: 'FeatureCollection',
	features: [
		{
			type: 'Feature',
			geometry: {
				type: 'MultiLineString',
				coordinates: [
					[
						[86.8721668, 27.9049154, 4739.0],
						[86.8720561, 27.9048113, 4738.0],
						[86.8719488, 27.9051147, 4740.0],
						[86.8724638, 27.9053707, 4746.0],
						[86.8728929, 27.9057784, 4753.0],
						[86.8730539, 27.9062714, 4758.0],
						[86.8738156, 27.9069066, 4775.0],
						[86.8738049, 27.9074091, 4792.0],
						[86.8744808, 27.9079495, 4812.0],
						[86.8747919, 27.9085753, 4839.0],
						[86.8761116, 27.9100448, 4899.0],
						[86.8763691, 27.9104904, 4916.0],
						[86.8763905, 27.9107085, 4927.0],
						[86.8766158, 27.9109076, 4931.0],
						[86.8766266, 27.9113342, 4953.0],
						[86.8768304, 27.9113627, 4950.0],
						[86.8773722, 27.9133157, 5016.0],
						[86.8773722, 27.9139225, 5030.0],
						[86.8772435, 27.9145671, 5036.0],
						[86.8774151, 27.916084, 5101.0],
						[86.8775814, 27.9179801, 5182.0],
						[86.8775922, 27.9198713, 5264.0],
						[86.8773213, 27.920042, 5281.0],
						[86.8775197, 27.9201747, 5281.0],
						[86.8773749, 27.9202031, 5286.0],
						[86.8772917, 27.9206203, 5310.0],
						[86.8770799, 27.9210374, 5336.0],
						[86.8768063, 27.9210658, 5344.0],
						[86.8766668, 27.9212602, 5352.0],
						[86.876581, 27.9212222, 5352.0],
						[86.8765541, 27.9213265, 5353.0],
						[86.8767204, 27.9216583, 5353.0],
						[86.877332, 27.9219759, 5372.0],
						[86.8776753, 27.9223456, 5378.0],
						[86.8779274, 27.9230945, 5397.0],
						[86.8778523, 27.9232841, 5404.0],
						[86.8780401, 27.9237107, 5431.0],
						[86.878378, 27.9240662, 5460.0],
						[86.8785658, 27.9246539, 5489.0],
						[86.8788957, 27.9251279, 5517.0],
						[86.8789815, 27.925526, 5518.0],
					],
				],
				bbox: [86.8789815, 27.925526, 86.8699049, 27.9048018],
			},
			properties: {
				weight: 3,
				day: '7',
				name: 'Chhukung - Chhuking Ri - Chhukung',
				distance: '3.49 mi / 5.61 km',
				time: '4h 30m',
				startAlt: '15,535',
				peakAlt: '18,104',
				endAlt: '15,535',
				total_climb: '2,497',
				descent: '2,510',
				color: '#D75F58',
				src: 'https://www.gpsies.com/map.do?fileId=qxgvfbjypqcoozdz',
				desc: 'Generated by GPSies.com https://www.gpsies.com/',
			},
		},
	],
};

const chhukung_to_kongma_la_to_lobuche_8 = {
	type: 'FeatureCollection',
	features: [
		{
			type: 'Feature',
			geometry: {
				type: 'MultiLineString',
				coordinates: [],
				bbox: [86.871974, 27.9484262, 86.8105342, 27.9044794],
			},
			properties: {
				weight: 3,
				day: '8',
				name: 'Chhukung - Kongma La Pass - Lobuche',
				distance: '5.79 mi / 9.31 km',
				time: '11h 30m',
				startAlt: '15,535',
				peakAlt: '18,058',
				endAlt: '16,210',
				total_climb: '2,753',
				descent: '2,159',
				color: '#D04D53',
				src: 'https://www.gpsies.com/map.do?fileId=ammnqzsjoeujwhwt',
				desc: 'Generated by GPSies.com https://www.gpsies.com/',
			},
		},
	],
};

const lobuche_to_ebc_to_gorak_shep_10 = {
	type: 'FeatureCollection',
	features: [
		{
			type: 'Feature',
			geometry: {
				type: 'MultiLineString',
				coordinates: [],
				bbox: [86.85706, 28.00424, 86.81052, 27.94793],
			},
			properties: {
				weight: 3,
				day: '10',
				name: 'Lobuche - Everest Base Camp - Gorak Shep',
				distance: '8.06 mi / 12.97 km',
				time: '10h 00m',
				startAlt: '16,210',
				peakAlt: '17,600',
				endAlt: '16,942',
				total_climb: '',
				descent: '',
				color: '#C93A4D',
				src: 'https://www.gpsies.com/map.do?fileId=bbckpacnkeoptfta',
				desc: 'Generated by GPSies.com https://www.gpsies.com/',
			},
		},
	],
};

const gorak_shep_to_kala_patthar_to_lobuche_12 = {
	type: 'FeatureCollection',
	features: [
		{
			type: 'Feature',
			geometry: {
				type: 'MultiLineString',
				coordinates: [],
				bbox: [86.83048, 27.9957, 86.81305, 27.95395],
			},
			properties: {
				weight: 3,
				day: '12',
				name: 'Gorak Shep - Kala Patthar - Lobuche',
				distance: '4.77 mi / 7.67 km',
				time: '8h 30m',
				startAlt: '16,942',
				peakAlt: '18,519',
				endAlt: '16,210',
				total_climb: '',
				descent: '',
				color: '#C22848',
				src: 'https://www.gpsies.com/map.do?fileId=ucopxslfokytnmfw',
				desc: 'Generated by GPSies.com https://www.gpsies.com/',
			},
		},
	],
};

const dzongla_to_thangnak_14 = {
	type: 'FeatureCollection',
	features: [
		{
			type: 'Feature',
			geometry: {
				type: 'MultiLineString',
				coordinates: [],
				bbox: [86.7737207, 27.9621109, 86.6937696, 27.9396686],
			},
			properties: {
				weight: 3,
				day: '14',
				name: 'Dzongla - Cho La Pass - Thangnak',
				distance: '4.98 mi / 8.01 km',
				time: '7h 00m',
				startAlt: '15,850',
				peakAlt: '17,625',
				endAlt: '15,420',
				total_climb: '2,067',
				descent: '2,530',
				color: '#C52447',
				src: 'https://www.gpsies.com/map.do?fileId=vduerqdjdjhjmnqj',
				desc: 'Generated by GPSies.com https://www.gpsies.com/',
			},
		},
	],
};

const thangnak_to_gokyo_15 = {
	type: 'FeatureCollection',
	features: [
		{
			type: 'Feature',
			geometry: {
				type: 'MultiLineString',
				coordinates: [],
				bbox: [86.7737207, 27.9621109, 86.6937696, 27.9396686],
			},
			properties: {
				weight: 3,
				day: '15',
				name: 'Thangnak - Gokyo',
				distance: '2.28 mi / 3.66 km',
				time: '3h 00m',
				startAlt: '15,420',
				peakAlt: '',
				endAlt: '15,720',
				total_climb: '295',
				descent: '554',
				color: '#CE334D',
				src: 'https://www.gpsies.com/map.do?fileId=vduerqdjdjhjmnqj',
				desc: 'Generated by GPSies.com https://www.gpsies.com/',
			},
		},
	],
};

const gokyo_to_gokyo_ri_16 = {
	type: 'FeatureCollection',
	features: [
		{
			type: 'Feature',
			geometry: {
				type: 'MultiLineString',
				coordinates: [],
				bbox: [86.694686, 27.962149, 86.6829169, 27.9536614],
			},
			properties: {
				weight: 3,
				day: '16',
				name: 'Gokyo - Gokyo Ri - Gokyo',
				distance: '2.11 mi / 3.39 km',
				time: '4h 30m',
				startAlt: '15,720',
				peakAlt: '17,989',
				endAlt: '15,720',
				total_climb: '1,972',
				descent: '1,969',
				color: '#D84152',
				src: 'https://www.gpsies.com/map.do?fileId=dmrswzqbobsnokqs',
				desc: 'Generated by GPSies.com https://www.gpsies.com/',
			},
		},
	],
};

const gokyo_to_marulung_18 = {
	type: 'FeatureCollection',
	features: [
		{
			type: 'Feature',
			geometry: {
				type: 'MultiLineString',
				coordinates: [],
				bbox: [86.6939708, 27.95473, 86.63578, 27.8882461],
			},
			properties: {
				weight: 3,
				day: '18',
				name: 'Gokyo - Renjo La Pass - Marulung',
				distance: '8.25 mi / 13.27 km',
				time: '9h 00m',
				startAlt: '15,574',
				peakAlt: '17,680',
				endAlt: '13,566',
				total_climb: '2,106',
				descent: '4,140',
				color: '#E15058',
				src: 'https://www.gpsies.com/map.do?fileId=eimshtzesuwpkvxg',
				desc: 'Generated by GPSies.com https://www.gpsies.com/',
			},
		},
	],
};

const marulung_to_namche_bazaar_19 = {
	type: 'FeatureCollection',
	features: [
		{
			type: 'Feature',
			geometry: {
				type: 'MultiLineString',
				coordinates: [],
				bbox: [86.7105066, 27.8884168, 86.6377651, 27.8038494],
			},
			properties: {
				weight: 3,
				day: '19',
				name: 'Marulung - Namche Bazar',
				distance: '9.87 mi / 15.88 km',
				time: '6h 00m',
				startAlt: '13,566',
				peakAlt: '',
				endAlt: '11,286',
				total_climb: '906',
				descent: '3,241',
				color: '#EB5F5D',
				src: 'https://www.gpsies.com/map.do?fileId=iigdmqlrvgawumdk',
				desc: 'Generated by GPSies.com https://www.gpsies.com/',
			},
		},
	],
};

const dayWiseDataG = {
	'7': chhukung_to_chhukung_ri_to_chhukung_7,
	'8': chhukung_to_kongma_la_to_lobuche_8,
	'10': lobuche_to_ebc_to_gorak_shep_10,
	'12': gorak_shep_to_kala_patthar_to_lobuche_12,
	'14': dzongla_to_thangnak_14,
	'15': thangnak_to_gokyo_15,
	'16': gokyo_to_gokyo_ri_16,
	'18': gokyo_to_marulung_18,
	'19': marulung_to_namche_bazaar_19,
};

const getDayWiseDataG = () => dayWiseDataG;

export { getDayWiseDataG };
